# Generated by Django 4.1.7 on 2023-03-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
