# Generated by Django 4.1.7 on 2023-03-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_destination_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
