# Generated by Django 4.1.7 on 2023-03-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_name_destination_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='message',
            new_name='messagas',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='subject',
        ),
        migrations.AddField(
            model_name='destination',
            name='subjectas',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
