# Generated by Django 4.1.7 on 2023-03-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_message_destination_messagas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
